/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeems;

import java.awt.Color;
import java.sql.ResultSet;
import java.util.Date;
import java.util.Formatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Salman
 */
public class EMS_UI extends javax.swing.JFrame {

    private EmployeeMS employeeManagmentSystem;

    /**
     * Creates new form EMS_UI
     */
    public EMS_UI() {
        initComponents();
        employeeManagmentSystem = new EmployeeMS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headPnl = new javax.swing.JPanel();
        emsLogo = new javax.swing.JLabel();
        emsTitle1 = new javax.swing.JLabel();
        emsTitle2 = new javax.swing.JLabel();
        bodyPnl = new javax.swing.JPanel();
        emsTabs = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        homeIntro = new javax.swing.JLabel();
        hireTab = new javax.swing.JPanel();
        heading_H = new javax.swing.JLabel();
        eNameLbl_H = new javax.swing.JLabel();
        eNameTxt_H = new javax.swing.JTextField();
        eAgeLbl_H = new javax.swing.JLabel();
        eAgeTxt_H = new javax.swing.JTextField();
        eSalaryLbl_H = new javax.swing.JLabel();
        eSalaryTxt_H = new javax.swing.JTextField();
        eDOALbl_H = new javax.swing.JLabel();
        hireBtn_H = new javax.swing.JButton();
        result_H = new javax.swing.JLabel();
        eDOATxt_H = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fireTab = new javax.swing.JPanel();
        heading_F = new javax.swing.JLabel();
        intro_F = new javax.swing.JLabel();
        eNameLbl_F = new javax.swing.JLabel();
        eNameTxt_F = new javax.swing.JTextField();
        eAgeLbl_F = new javax.swing.JLabel();
        eAgeTxt_F = new javax.swing.JTextField();
        eSalaryLbl_F = new javax.swing.JLabel();
        eSalaryTxt_F = new javax.swing.JTextField();
        eDOALbl_F = new javax.swing.JLabel();
        eDOATxt_F = new javax.swing.JTextField();
        fireBtn_F = new javax.swing.JButton();
        result_F = new javax.swing.JLabel();
        eIdLbl_F = new javax.swing.JLabel();
        eIdTxt_F = new javax.swing.JTextField();
        eIdBtn_F = new javax.swing.JButton();
        intro_F1 = new javax.swing.JLabel();
        editTab = new javax.swing.JPanel();
        heading_E = new javax.swing.JLabel();
        eNameLbl_E = new javax.swing.JLabel();
        eNameTxt_E = new javax.swing.JTextField();
        eAgeLbl_E = new javax.swing.JLabel();
        eAgeTxt_E = new javax.swing.JTextField();
        eSalaryLbl_E = new javax.swing.JLabel();
        eSalaryTxt_E = new javax.swing.JTextField();
        eDOALbl_E = new javax.swing.JLabel();
        eDOATxt_E = new javax.swing.JTextField();
        editBtn_E = new javax.swing.JButton();
        result_E = new javax.swing.JLabel();
        eIdLbl_E = new javax.swing.JLabel();
        eIdTxt_E = new javax.swing.JTextField();
        eIdBtn_E = new javax.swing.JButton();
        intro_F2 = new javax.swing.JLabel();
        intro_F3 = new javax.swing.JLabel();
        rprtTab = new javax.swing.JPanel();
        selectrprtLbl = new javax.swing.JLabel();
        rprtMenuScroll = new javax.swing.JScrollPane();
        rprtMenuList = new javax.swing.JList<>();
        generateRprtBtn = new javax.swing.JButton();
        resultScroll = new javax.swing.JScrollPane();
        rprtResult = new javax.swing.JTable();
        abtTab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        emsLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeems/EMSLOGO.jpeg"))); // NOI18N

        emsTitle1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        emsTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emsTitle1.setText("EMPLOYEE MANAGMENT");

        emsTitle2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        emsTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emsTitle2.setText("SYSTEM");

        javax.swing.GroupLayout headPnlLayout = new javax.swing.GroupLayout(headPnl);
        headPnl.setLayout(headPnlLayout);
        headPnlLayout.setHorizontalGroup(
            headPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPnlLayout.createSequentialGroup()
                .addComponent(emsLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emsTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emsTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        headPnlLayout.setVerticalGroup(
            headPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emsLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headPnlLayout.createSequentialGroup()
                .addComponent(emsTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emsTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        emsTabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                emsTabsStateChanged(evt);
            }
        });

        homeIntro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeems/EMS.png"))); // NOI18N

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeIntro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeIntro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        emsTabs.addTab("Home", homeTab);

        heading_H.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        heading_H.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading_H.setText("Hire a Employee");

        eNameLbl_H.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eNameLbl_H.setText("Employee's Name :");

        eAgeLbl_H.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eAgeLbl_H.setText("Employee's Age :");

        eSalaryLbl_H.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eSalaryLbl_H.setText("Employee's Salary :");

        eDOALbl_H.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eDOALbl_H.setText("Date Of Appointment :");

        hireBtn_H.setText("HIRE");
        hireBtn_H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hireBtn_HActionPerformed(evt);
            }
        });

        result_H.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        result_H.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        eDOATxt_H.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));

        jLabel1.setText("- Fill the form to hire an employee or want to enroll excisting employee's data in EMS.");

        jLabel2.setText("- NOTE  : Fill the every fileds with appropiate data then click on hire button.");

        javax.swing.GroupLayout hireTabLayout = new javax.swing.GroupLayout(hireTab);
        hireTab.setLayout(hireTabLayout);
        hireTabLayout.setHorizontalGroup(
            hireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heading_H, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hireTabLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(hireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hireTabLayout.createSequentialGroup()
                        .addComponent(eAgeLbl_H, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eAgeTxt_H, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                    .addGroup(hireTabLayout.createSequentialGroup()
                        .addComponent(eNameLbl_H, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eNameTxt_H))
                    .addGroup(hireTabLayout.createSequentialGroup()
                        .addComponent(eDOALbl_H, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eDOATxt_H))
                    .addGroup(hireTabLayout.createSequentialGroup()
                        .addComponent(eSalaryLbl_H, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eSalaryTxt_H))
                    .addComponent(hireBtn_H, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
            .addGroup(hireTabLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(result_H, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(hireTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(hireTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        hireTabLayout.setVerticalGroup(
            hireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hireTabLayout.createSequentialGroup()
                .addComponent(heading_H, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(hireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eNameLbl_H, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eNameTxt_H, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eAgeLbl_H, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eAgeTxt_H, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eSalaryLbl_H, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eSalaryTxt_H, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eDOALbl_H, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(eDOATxt_H))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hireBtn_H, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result_H, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        emsTabs.addTab("Hire Employee", hireTab);

        heading_F.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        heading_F.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading_F.setText("Fire an Employee");

        intro_F.setText("- Enter the Employee's ID to fire an employee or want to delete excisting employee's record from EMS.");

        eNameLbl_F.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eNameLbl_F.setText("Employee's Name :");

        eAgeLbl_F.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eAgeLbl_F.setText("Employee's Age :");

        eSalaryLbl_F.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eSalaryLbl_F.setText("Employee's Salary :");

        eDOALbl_F.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eDOALbl_F.setText("Date Of Appointment :");

        fireBtn_F.setText("FIRE");
        fireBtn_F.setEnabled(false);
        fireBtn_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireBtn_FActionPerformed(evt);
            }
        });

        result_F.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        result_F.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        eIdLbl_F.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        eIdLbl_F.setText("Enter Employee's ID to Fire :");

        eIdTxt_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIdTxt_FActionPerformed(evt);
            }
        });

        eIdBtn_F.setText("Submit");
        eIdBtn_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIdBtn_FActionPerformed(evt);
            }
        });

        intro_F1.setText("- NOTE: Give the employee's ID, then see data and make sure then press Fire button (see ID in reports).");

        javax.swing.GroupLayout fireTabLayout = new javax.swing.GroupLayout(fireTab);
        fireTab.setLayout(fireTabLayout);
        fireTabLayout.setHorizontalGroup(
            fireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heading_F, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
            .addGroup(fireTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fireTabLayout.createSequentialGroup()
                        .addComponent(intro_F1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fireTabLayout.createSequentialGroup()
                        .addGroup(fireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fireTabLayout.createSequentialGroup()
                                .addComponent(eIdLbl_F, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eIdTxt_F, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eIdBtn_F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(fireTabLayout.createSequentialGroup()
                                .addComponent(eAgeLbl_F, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eAgeTxt_F, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                            .addGroup(fireTabLayout.createSequentialGroup()
                                .addComponent(eNameLbl_F, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eNameTxt_F))
                            .addGroup(fireTabLayout.createSequentialGroup()
                                .addComponent(eDOALbl_F, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eDOATxt_F, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                            .addGroup(fireTabLayout.createSequentialGroup()
                                .addComponent(eSalaryLbl_F, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eSalaryTxt_F))
                            .addComponent(fireBtn_F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(fireTabLayout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(result_F, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE))
                            .addComponent(intro_F, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))))
        );
        fireTabLayout.setVerticalGroup(
            fireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fireTabLayout.createSequentialGroup()
                .addComponent(heading_F, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intro_F, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intro_F1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eIdTxt_F)
                    .addComponent(eIdLbl_F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eIdBtn_F, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eNameLbl_F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eNameTxt_F, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eAgeLbl_F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eAgeTxt_F, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eSalaryLbl_F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eSalaryTxt_F, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fireTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eDOALbl_F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eDOATxt_F, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fireBtn_F, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result_F, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        emsTabs.addTab("Fire Employee", fireTab);

        heading_E.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        heading_E.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading_E.setText("Edit an Employee's Record");

        eNameLbl_E.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eNameLbl_E.setText("Employee's Name :");

        eAgeLbl_E.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eAgeLbl_E.setText("Employee's Age :");

        eSalaryLbl_E.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eSalaryLbl_E.setText("Employee's Salary :");

        eDOALbl_E.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        eDOALbl_E.setText("Date Of Appointment :");

        editBtn_E.setText("UPDATE");
        editBtn_E.setEnabled(false);
        editBtn_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn_EActionPerformed(evt);
            }
        });

        result_E.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        result_E.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        eIdLbl_E.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        eIdLbl_E.setText("Enter Employee's ID to Edit :");

        eIdBtn_E.setText("Submit");
        eIdBtn_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIdBtn_EActionPerformed(evt);
            }
        });

        intro_F2.setText("- NOTE: Date of Appointment is unchangable, and if dont known ID then see in report section.");

        intro_F3.setText("- Enter Employee's ID then Fill the form in which correction necessary to edit an excisting employee record in EMS.");

        javax.swing.GroupLayout editTabLayout = new javax.swing.GroupLayout(editTab);
        editTab.setLayout(editTabLayout);
        editTabLayout.setHorizontalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heading_E, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
            .addGroup(editTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editTabLayout.createSequentialGroup()
                        .addComponent(intro_F2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(editTabLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(result_E, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(229, Short.MAX_VALUE))
                    .addGroup(editTabLayout.createSequentialGroup()
                        .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editTabLayout.createSequentialGroup()
                                .addComponent(eIdLbl_E, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eIdTxt_E, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eIdBtn_E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(editTabLayout.createSequentialGroup()
                                .addComponent(eAgeLbl_E, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eAgeTxt_E, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                            .addGroup(editTabLayout.createSequentialGroup()
                                .addComponent(eNameLbl_E, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eNameTxt_E))
                            .addGroup(editTabLayout.createSequentialGroup()
                                .addComponent(eDOALbl_E, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eDOATxt_E, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                            .addGroup(editTabLayout.createSequentialGroup()
                                .addComponent(eSalaryLbl_E, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eSalaryTxt_E))
                            .addComponent(editBtn_E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))
                    .addGroup(editTabLayout.createSequentialGroup()
                        .addComponent(intro_F3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))))
        );
        editTabLayout.setVerticalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTabLayout.createSequentialGroup()
                .addComponent(heading_E, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intro_F3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intro_F2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eIdLbl_E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eIdTxt_E)
                    .addComponent(eIdBtn_E, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eNameLbl_E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eNameTxt_E, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eAgeLbl_E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eAgeTxt_E, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eSalaryLbl_E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eSalaryTxt_E, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eDOALbl_E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eDOATxt_E, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn_E, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result_E, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        emsTabs.addTab("Edit Employee's Record", editTab);

        selectrprtLbl.setText("Select Report Type :");

        rprtMenuList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fetch Employee Record",
                "Accending Employee Names",
                "Decending Employee Names",
                "Search Employee With Name",
                "Show Salary Details",
                "Employee with high & low salary",
                "Employee with high & low age",
                "Employees with ASC DOA",
                "Summary on Employee\'s Record"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        rprtMenuList.setSelectedIndex(0);
        rprtMenuScroll.setViewportView(rprtMenuList);

        generateRprtBtn.setText("Generate Report");
        generateRprtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateRprtBtnActionPerformed(evt);
            }
        });

        rprtResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [200][5],
            new String [] {
                "Employee ID", "Employee Name", "Employee Age", "Employee Salary", "Appointment Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultScroll.setViewportView(rprtResult);
        if (rprtResult.getColumnModel().getColumnCount() > 0) {
            rprtResult.getColumnModel().getColumn(0).setMaxWidth(100);
            rprtResult.getColumnModel().getColumn(1).setResizable(false);
            rprtResult.getColumnModel().getColumn(2).setMaxWidth(100);
            rprtResult.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout rprtTabLayout = new javax.swing.GroupLayout(rprtTab);
        rprtTab.setLayout(rprtTabLayout);
        rprtTabLayout.setHorizontalGroup(
            rprtTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rprtTabLayout.createSequentialGroup()
                .addGroup(rprtTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rprtTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(selectrprtLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(rprtMenuScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(generateRprtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
        );
        rprtTabLayout.setVerticalGroup(
            rprtTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rprtTabLayout.createSequentialGroup()
                .addGroup(rprtTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rprtTabLayout.createSequentialGroup()
                        .addComponent(selectrprtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rprtMenuScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateRprtBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .addComponent(resultScroll))
                .addContainerGap())
        );

        emsTabs.addTab("Generate Reports", rprtTab);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeems/ABOUT.png"))); // NOI18N

        javax.swing.GroupLayout abtTabLayout = new javax.swing.GroupLayout(abtTab);
        abtTab.setLayout(abtTabLayout);
        abtTabLayout.setHorizontalGroup(
            abtTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        abtTabLayout.setVerticalGroup(
            abtTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        emsTabs.addTab("About", abtTab);

        javax.swing.GroupLayout bodyPnlLayout = new javax.swing.GroupLayout(bodyPnl);
        bodyPnl.setLayout(bodyPnlLayout);
        bodyPnlLayout.setHorizontalGroup(
            bodyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emsTabs)
        );
        bodyPnlLayout.setVerticalGroup(
            bodyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emsTabs)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eIdTxt_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIdTxt_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eIdTxt_FActionPerformed

    private void hireBtn_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hireBtn_HActionPerformed
        String eName = eNameTxt_H.getText();
        Date eDOA = (Date) eDOATxt_H.getValue();
        int eAge, eSalary;
        try{
            eAge = Integer.parseInt(eAgeTxt_H.getText());
            eSalary = Integer.parseInt(eSalaryTxt_H.getText());
        }catch(Exception e){
           eAge = eSalary = 0; 
        }
        boolean somethingMissing = false;
        if(eName.equals("")){
            eNameTxt_H.setBackground(Color.red);
            somethingMissing = true;
        } 
        if(eAge <= 0){
            eAgeTxt_H.setBackground(Color.red);
            somethingMissing = true;
        }
        if(eSalary <= 0){
            eSalaryTxt_H.setBackground(Color.red);
            somethingMissing = true;
        }
        if(somethingMissing)
            return;
        else{
            Formatter f = new Formatter();
            f.format("%te-%th-%tY", eDOA, eDOA, eDOA);
            boolean done = employeeManagmentSystem.hireEmployee(eName, eSalary, eAge, f.toString());
            if(done){
                result_H.setText("Succes");
                eNameTxt_H.setText("");
                eAgeTxt_H.setText("");
                eSalaryTxt_H.setText("");
            }
            else
                result_H.setText("Failed");
        }
    }//GEN-LAST:event_hireBtn_HActionPerformed

    private void eIdBtn_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIdBtn_FActionPerformed
        result_F.setText("");
        String eId = eIdTxt_F.getText();
        if(eId.equals("")){
            eIdTxt_F.setBackground(Color.red);
            return;
        }
        else{
            try{
               String[] data = employeeManagmentSystem.fireEmployee( Integer.parseInt(eId) );
               if(data == null){
                   result_F.setText("Invalid Employee ID, Failed!");
               }
               else{
                eAgeTxt_F.setText(data[1]); 
                eNameTxt_F.setText(data[0]);
                eSalaryTxt_F.setText(data[2]);
                eDOATxt_F.setText(data[3]);
                fireBtn_F.setEnabled(true);
               }
            }catch(Exception e){e.printStackTrace();}
        }
    }//GEN-LAST:event_eIdBtn_FActionPerformed

    private void fireBtn_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireBtn_FActionPerformed
        boolean fired = employeeManagmentSystem.fireEmployee(eIdTxt_F.getText());
        if(fired){
            result_F.setText("Succeed");
            eNameTxt_F.setText("");
            eAgeTxt_F.setText("");
            eSalaryTxt_F.setText("");
            eDOATxt_F.setText("");
            eIdTxt_F.setText("");
            fireBtn_F.setEnabled(false);
        }
        else
            result_F.setText("Failed");
    }//GEN-LAST:event_fireBtn_FActionPerformed

    private void eIdBtn_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIdBtn_EActionPerformed
        String eId = eIdTxt_E.getText();
        if(eId.equals("")){
            eIdTxt_E.setBackground(Color.red);
            return;
        }
        else{
            try{
               String[] data = employeeManagmentSystem.editEmployee( Integer.parseInt(eId) );
               if(data == null){
                   result_E.setText("Invalid Employee ID, Failed!");
               }
               else{
                eAgeTxt_E.setText(data[1]); 
                eNameTxt_E.setText(data[0]);
                eSalaryTxt_E.setText(data[2]);
                eDOATxt_E.setText(data[3]);
                editBtn_E.setEnabled(true);
               }
            }catch(Exception e){e.printStackTrace();}
        }
    }//GEN-LAST:event_eIdBtn_EActionPerformed

    private void generateRprtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateRprtBtnActionPerformed
        String rType = rprtMenuList.getSelectedValue();
        if(rType.equals("Search Employee With Name"))
            rType += ">" + JOptionPane.showInputDialog(this, "Enter Employee\'s Name to Search?");
        
        try{
            ResultSet r = employeeManagmentSystem.GenerateReport(rType);
            if(r == null )
                return;
            else{
                for(int i = 0; i < rprtResult.getRowCount(); i++)
                        for(int j = 0; j < rprtResult.getColumnCount(); j++)
                            rprtResult.setValueAt("", i, j);
                if(rType.equals("Show Salary Details")){
                    String str = "";
                    if(r.next()){
                        str += "All employee\'s Salary detail:\n";
                        str += "Average Salary = " + r.getObject(1) + "\n";
                        str += "Max Salary = " + r.getObject(2) + "\n";
                        str += "Min Salary = " + r.getObject(3) + "\n";
                        str += "Sum of Salaries = " + r.getObject(4) + "\n";
                        str += "of " + r.getObject(5) + "(All) Employees.\n";
                    }
                    JOptionPane.showMessageDialog(this, str);
                }
                else if(rType.equals("Summary on Employee\'s Record")){
                    String str = "";
                    if(r.next()){
                        str += "Summary on Employee\'s Record :\n";
                        str += "No of Employee = " + r.getObject(1) + "\n";
                        str += "Max Salary of an employee = " + r.getObject(2) + "\n";
                        str += "Min Salary of an employee = " + r.getObject(3) + "\n";
                        str += "Max Age of an employee = " + r.getObject(4) + "\n";
                        str += "Min Age of an employee = " + r.getObject(5) + "\n";
                        str += "Max D.O.A of an employee = " + r.getObject(6) + "\n";
                        str += "Min D.O.A of an employee = " + r.getObject(7) + "\n";
                    }
                    JOptionPane.showMessageDialog(this, str);
                }
                else{
                    int i;
                    for(i = 0; r.next(); i++){
                        for(int j = 0; j < 5; j++)
                            rprtResult.setValueAt(r.getObject(j+1)+"", i, j);
                    }
                    if(i == 0)
                        for(int j = 0; j < 5; j++)
                            rprtResult.setValueAt("No Result!", i, j);
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_generateRprtBtnActionPerformed

    private void editBtn_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn_EActionPerformed
        String employeeNewData[] = {
            eIdTxt_E.getText(),
            eNameTxt_E.getText(),
            eAgeTxt_E.getText(),
            eSalaryTxt_E.getText()
        }; 
        boolean edited = employeeManagmentSystem.editEmployee(employeeNewData);
        if(edited){
            result_E.setText("Succeed");
            eNameTxt_E.setText("");
            eAgeTxt_E.setText("");
            eSalaryTxt_E.setText("");
            eDOATxt_E.setText("");
            eIdTxt_E.setText("");
            editBtn_E.setEnabled(false);
        }
        else
            result_E.setText("Failed");
    }//GEN-LAST:event_editBtn_EActionPerformed

    private void emsTabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_emsTabsStateChanged
        result_H.setText("");
        result_F.setText("");
        result_E.setText("");
    }//GEN-LAST:event_emsTabsStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.employeeManagmentSystem.closeSystem();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMS_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMS_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMS_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMS_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EMS_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abtTab;
    private javax.swing.JPanel bodyPnl;
    private javax.swing.JLabel eAgeLbl_E;
    private javax.swing.JLabel eAgeLbl_F;
    private javax.swing.JLabel eAgeLbl_H;
    private javax.swing.JTextField eAgeTxt_E;
    private javax.swing.JTextField eAgeTxt_F;
    private javax.swing.JTextField eAgeTxt_H;
    private javax.swing.JLabel eDOALbl_E;
    private javax.swing.JLabel eDOALbl_F;
    private javax.swing.JLabel eDOALbl_H;
    private javax.swing.JTextField eDOATxt_E;
    private javax.swing.JTextField eDOATxt_F;
    private javax.swing.JSpinner eDOATxt_H;
    private javax.swing.JButton eIdBtn_E;
    private javax.swing.JButton eIdBtn_F;
    private javax.swing.JLabel eIdLbl_E;
    private javax.swing.JLabel eIdLbl_F;
    private javax.swing.JTextField eIdTxt_E;
    private javax.swing.JTextField eIdTxt_F;
    private javax.swing.JLabel eNameLbl_E;
    private javax.swing.JLabel eNameLbl_F;
    private javax.swing.JLabel eNameLbl_H;
    private javax.swing.JTextField eNameTxt_E;
    private javax.swing.JTextField eNameTxt_F;
    private javax.swing.JTextField eNameTxt_H;
    private javax.swing.JLabel eSalaryLbl_E;
    private javax.swing.JLabel eSalaryLbl_F;
    private javax.swing.JLabel eSalaryLbl_H;
    private javax.swing.JTextField eSalaryTxt_E;
    private javax.swing.JTextField eSalaryTxt_F;
    private javax.swing.JTextField eSalaryTxt_H;
    private javax.swing.JButton editBtn_E;
    private javax.swing.JPanel editTab;
    private javax.swing.JLabel emsLogo;
    private javax.swing.JTabbedPane emsTabs;
    private javax.swing.JLabel emsTitle1;
    private javax.swing.JLabel emsTitle2;
    private javax.swing.JButton fireBtn_F;
    private javax.swing.JPanel fireTab;
    private javax.swing.JButton generateRprtBtn;
    private javax.swing.JPanel headPnl;
    private javax.swing.JLabel heading_E;
    private javax.swing.JLabel heading_F;
    private javax.swing.JLabel heading_H;
    private javax.swing.JButton hireBtn_H;
    private javax.swing.JPanel hireTab;
    private javax.swing.JLabel homeIntro;
    private javax.swing.JPanel homeTab;
    private javax.swing.JLabel intro_F;
    private javax.swing.JLabel intro_F1;
    private javax.swing.JLabel intro_F2;
    private javax.swing.JLabel intro_F3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane resultScroll;
    private javax.swing.JLabel result_E;
    private javax.swing.JLabel result_F;
    private javax.swing.JLabel result_H;
    private javax.swing.JList<String> rprtMenuList;
    private javax.swing.JScrollPane rprtMenuScroll;
    private javax.swing.JTable rprtResult;
    private javax.swing.JPanel rprtTab;
    private javax.swing.JLabel selectrprtLbl;
    // End of variables declaration//GEN-END:variables
}
